params ["_AOIndex"];
private _pos = ["ENEMY_ARTILLERY"] call DRO2026_fnc_getTheaterNode;
private _taskName = format ["D26_ARTY_%1", floor random 1000000];
private _marker = format ["D26_M_ARTY_%1", floor random 1000000];
private _color = if (isNil "markerColorEnemy") then {"ColorOPFOR"} else {markerColorEnemy};
createMarker [_marker, _pos]; _marker setMarkerShape "ELLIPSE"; _marker setMarkerSize [420,420]; _marker setMarkerBrush "Border"; _marker setMarkerColor _color; _marker setMarkerAlpha 0.58; _marker setMarkerText " Предполагаемый район артиллерии";
private _role = if (enemySide == west) then {"ARTILLERY_WEST"} else {"ARTILLERY_EAST"};
private _fallback = if (enemySide == west) then {"B_MBT_01_arty_F"} else {"O_MBT_02_arty_F"};
private _class = [_role, _fallback] call DRO2026_fnc_getRoleClass;
private _arty = createVehicle [_class, _pos, [], 0, "NONE"];
if (isNull _arty || {count getArtilleryAmmo [_arty] == 0}) then {
    if (!isNull _arty) then {deleteVehicle _arty};
    _class = if (enemySide == west) then {"B_Mortar_01_F"} else {"O_Mortar_01_F"};
    _arty = createVehicle [_class, _pos, [], 0, "NONE"];
};
if (isNull _arty) exitWith {[_AOIndex] call DRO2026_fnc_objectiveLogisticsHub};
private _artyGroup = enemySide createVehicleCrew _arty;
_arty setDir random 360; DRO2026_managedVehicles pushBackUnique _arty;
if (!isNull _artyGroup) then {[_artyGroup, false] call DRO2026_fnc_registerManagedGroup};
private _positions = [_pos];
for "_i" from 1 to 3 do {private _candidate = [_pos, 320, 850, 10, 0, 0.3, 0, [], [_pos, _pos]] call BIS_fnc_findSafePos; if !(_candidate isEqualTo [0,0,0]) then {_positions pushBack _candidate}};
[_pos, 3, 5, 110] call DRO2026_fnc_spawnGuard;
DRO2026_sites pushBack createHashMapFromArray [["type", "ARTILLERY_SITE"], ["position", _pos], ["object", _arty], ["positions", _positions]];
private _title = "Контрбатарейная охота";
private _desc = "Артиллерийский расчёт реально занимает огневые позиции, ведёт короткие серии по выявленным союзным точкам и после двух огневых задач меняет место. Маркер показывает уточняемый район, а не постоянную точку. Найдите систему по вспышкам, звуку, БПЛА или маршруту отхода и уничтожьте её.";
private _meta = createHashMapFromArray [["type", "ARTILLERY_HUNT"], ["object", _arty], ["positions", _positions]];
[_taskName, _desc, _title, _marker, "destroy", _pos, 0.88, [], _meta] call DRO2026_fnc_createObjectiveRecord;
[_arty, _positions, _taskName, _marker] spawn DRO2026_fnc_artilleryLoop;
[_taskName, _arty] spawn {params ["_task", "_arty"]; waitUntil {sleep 2; !alive _arty}; [_task, "ARTILLERY_DESTROYED", [["enemyArtilleryAmmo", -34], ["enemySupply", -8]]] call DRO2026_fnc_completeObjective};
[] spawn {waitUntil {sleep 1; missionNamespace getVariable ["playersReady", 0] == 1}; sleep 8; ["ARTILLERY_TASK"] call DRO2026_fnc_hqVoice};
_taskName
