params ["_AOIndex"];
private _pos = ["ENEMY_TACTICAL_REAR"] call DRO2026_fnc_getTheaterNode;
private _taskName = format ["D26_REAR_%1", floor random 1000000];
private _marker = format ["D26_M_REAR_%1", floor random 1000000];
private _color = if (isNil "markerColorEnemy") then {"ColorOPFOR"} else {markerColorEnemy};
createMarker [_marker, _pos]; _marker setMarkerShape "ELLIPSE"; _marker setMarkerSize [420,420]; _marker setMarkerBrush "Border"; _marker setMarkerColor _color; _marker setMarkerAlpha 0.58; _marker setMarkerText " Узел тыловой связи";
private _relay = createVehicle ["Land_TTowerSmall_1_F", _pos getPos [25, 50], [], 0, "NONE"];
private _suffix = [enemySide] call DRO2026_fnc_getSideSuffix;
private _role = format ["LOGISTICS_%1", _suffix];
private _fuelFallback = switch (enemySide) do {case west: {"B_Truck_01_fuel_F"}; case resistance: {"I_Truck_02_fuel_F"}; default {"O_Truck_03_fuel_F"}};
private _ammoFallback = switch (enemySide) do {case west: {"B_Truck_01_ammo_F"}; case resistance: {"I_Truck_02_ammo_F"}; default {"O_Truck_03_ammo_F"}};
private _fuelClass = [_role, _fuelFallback, enemySide] call DRO2026_fnc_getSideRoleClass;
private _ammoClass = [_role, _ammoFallback, enemySide] call DRO2026_fnc_getSideRoleClass;
private _fuel = if (_fuelClass == "") then {objNull} else {createVehicle [_fuelClass, _pos getPos [22, 160], [], 0, "NONE"]};
private _ammo = if (_ammoClass == "") then {objNull} else {createVehicle [_ammoClass, _pos getPos [28, 225], [], 0, "NONE"]};
private _critical = [_relay, _fuel, _ammo] select {!isNull _x};
{if (_x isKindOf "AllVehicles") then {DRO2026_managedVehicles pushBackUnique _x}} forEach _critical;
if (count _critical < 2) exitWith {{if (!isNull _x) then {deleteVehicle _x}} forEach _critical; deleteMarker _marker; [_AOIndex] call DRO2026_fnc_objectiveLogisticsHub};
[_pos, 5, 8, 150] call DRO2026_fnc_spawnGuard;
DRO2026_sites pushBack createHashMapFromArray [["type", "REAR_LINK"], ["position", _pos], ["object", _relay], ["objects", _critical]];
private _title = "Отсечь тыл наступающей группировки";
private _desc = "Этот конкретный узел связывает передовые подразделения с топливом, боеприпасами и управлением. Уничтожьте ретранслятор и машины снабжения до начала усиленной реакции противника.";
private _meta = createHashMapFromArray [["type", "CUT_REAR"], ["critical", _critical]];
[_taskName, _desc, _title, _marker, "destroy", _pos, 0.9, [], _meta] call DRO2026_fnc_createObjectiveRecord;
[_taskName, _critical] spawn {params ["_task", "_critical"]; waitUntil {sleep 1; missionNamespace getVariable ["playersReady", 0] == 1 || {missionNamespace getVariable ["DRO2026_missionEnding", false]}}; private _deadline = time + 3300; waitUntil {sleep 3; ({!isNull _x && {alive _x}} count _critical) <= 1 || {time > _deadline} || {missionNamespace getVariable ["DRO2026_missionEnding", false]}}; if !(missionNamespace getVariable ["DRO2026_missionEnding", false]) then {if (({!isNull _x && {alive _x}} count _critical) <= 1) then {[_task, "TASK_COMPLETE", [["enemySupply", -24], ["enemyReinforcement", -26], ["enemyArtilleryAmmo", -10], ["enemyDroneStock", -7]]] call DRO2026_fnc_completeObjective} else {[_task, "FAILED", true] spawn BIS_fnc_taskSetState; missionNamespace setVariable [format ["%1Completed", _task], -1, true]; DRO2026_alertLevel = 0.9}}};
[] spawn {waitUntil {sleep 1; missionNamespace getVariable ["playersReady", 0] == 1 || {missionNamespace getVariable ["DRO2026_missionEnding", false]}}; if !(missionNamespace getVariable ["DRO2026_missionEnding", false]) then {sleep 8; ["NEW_TASK", "Штаб: Отрежьте конкретный узел снабжения наступающей группировки."] call DRO2026_fnc_hqVoice}};
_taskName
