/* DRO 2026 RC3 — single-player operation layer. */
DRO2026_VERSION = "1.2.0-rc3";
DRO2026_DEBUG = false;
DRO2026_AUTO_SAVE = true;

DRO2026_PHYSICAL_DRONE_LIMIT = 12;
DRO2026_ACTIVE_CONVOY_LIMIT = 3;
DRO2026_ACTIVE_CIV_TRAFFIC_LIMIT = 4;
DRO2026_GROUP_ACTIVATION_DISTANCE = 1800;
DRO2026_VEHICLE_ACTIVATION_DISTANCE = 2600;
DRO2026_PROP_ACTIVATION_DISTANCE = 450;
DRO2026_MIN_FPS_FOR_REINFORCEMENTS = 24;
DRO2026_CONTACT_TTL = 480;
DRO2026_CONTACT_REQUIRED_FOR_FPV = 0.62;
DRO2026_CONTACT_REQUIRED_FOR_LONG_RANGE = 0.74;
DRO2026_FPV_COOLDOWN = 70;
DRO2026_ISR_COOLDOWN = 150;
DRO2026_LONG_SUPPORT_COOLDOWN = 120;
DRO2026_ENEMY_FPV_MIN_INTERVAL = 55;
DRO2026_ENEMY_FPV_MAX_INTERVAL = 125;
DRO2026_LONG_RANGE_MIN_INTERVAL = 260;
DRO2026_LONG_RANGE_MAX_INTERVAL = 520;
DRO2026_CONVOY_MIN_ROUTE = 5500;
DRO2026_CONVOY_MAX_ROUTE = 14000;

DRO2026_OPERATION_TYPES = [
    "LOGISTICS_HUB", "LOGISTICS_RUN", "ARTILLERY_HUNT", "EW_HUNT",
    "CONVOY_INTERDICTION", "DRONE_SITE", "UAV_TEAM", "AIR_DEFENCE",
    "ISR_RECON", "CUT_REAR"
];

DRO2026_OPERATION_PACKAGES = [
    ["Срыв наступления", ["CUT_REAR", "LOGISTICS_RUN", "ARTILLERY_HUNT"]],
    ["Контрбатарейная операция", ["ISR_RECON", "ARTILLERY_HUNT", "LOGISTICS_RUN"]],
    ["Разрыв тыловой сети", ["LOGISTICS_HUB", "CONVOY_INTERDICTION", "AIR_DEFENCE"]],
    ["Подавление беспилотного контура", ["ISR_RECON", "UAV_TEAM", "DRONE_SITE"]],
    ["Охота за средствами поддержки", ["EW_HUNT", "ARTILLERY_HUNT", "LOGISTICS_HUB"]],
    ["Перехват снабжения", ["LOGISTICS_RUN", "CONVOY_INTERDICTION", "CUT_REAR"]],
    ["Воздушная угроза", ["AIR_DEFENCE", "DRONE_SITE", "LOGISTICS_HUB"]]
];

DRO2026_fnc_log = {
    params ["_message"];
    diag_log format ["[DRO2026] %1", _message];
    if (DRO2026_DEBUG && {hasInterface}) then {systemChat format ["DRO2026: %1", _message]};
};
