from pathlib import Path
import json, sys
ROOT=Path(__file__).resolve().parents[1]
read=lambda p:(ROOT/p).read_text(encoding='utf-8')
checks=[]
def check(name,ok,detail): checks.append({'name':name,'ok':bool(ok),'detail':detail})
cfg=read('dro2026/CfgFunctions.hpp')
selector=read('dro2026/functions/core/fn_selectConvoyClass.sqf')
side_role=read('dro2026/functions/core/fn_getSideRoleClass.sqf')
shorad=read('dro2026/functions/core/fn_materializeStrategicSHORAD.sqf')
infra=read('dro2026/functions/core/fn_createStrategicInfrastructure.sqf')
sanitize=read('dro2026/functions/core/fn_sanitizeLegacyPools.sqf')
strategic=read('dro2026/functions/core/fn_registerStrategicAssets.sqf')
primary=read('dro2026/functions/core/fn_getAssetPrimaryRole.sqf')
layered=read('dro2026/functions/core/fn_spawnLayeredAA.sqf')
point=read('dro2026/functions/core/fn_spawnPointDefenceGroup.sqf')
logistics=read('dro2026/functions/directors/fn_logisticsDirector.sqf')
objective_convoy=read('dro2026/functions/objectives/fn_objectiveConvoy.sqf')
objective_run=read('dro2026/functions/objectives/fn_objectiveLogisticsRun.sqf')
role_contract=read('dro2026/functions/core/fn_isAssetAllowedForRole.sqf')
mission=read('mission.sqm')
description=read('description.ext')
check('functions registered','class selectConvoyClass {};' in cfg and 'class materializeStrategicSHORAD {};' in cfg,'new helpers must be compiled')
check('convoy cargo specialization','_effectiveCargoType' in side_role and 'ARTILLERY_AMMO' in side_role and 'fuel' in side_role,'explicit cargo type or validated fallback class must preserve specialization')
check('convoy selector receives cargo','["_cargoType","GENERAL"' in side_role and '_effectiveCargoType,_fallback,"CARGO"' in side_role,'side role resolver must forward effective cargo specialization')
check('convoy prefers modded', 'count _specializedModded > 0' in selector and 'count _modded > 0' in selector and 'vanillaFallback' in selector,'vanilla is fallback only')
check('config-backed cargo specialization','_role == "LOGISTICS_FUEL"' in selector and '_role == "LOGISTICS_AMMO"' in selector,'transport config roles should outrank class-name heuristics')
check('fallback validated','[_fallback] call _isValid' in selector and '_registryRole == "") then {[]}' in selector,'fallback must obey side/scope/role/blocklist')
check('dedicated convoy contract','case "CONVOY_CARGO_POOL"' in role_contract and 'TRANSPORT_PERSONNEL' in role_contract.split('case "CONVOY_CARGO_POOL"')[1].split('};',1)[0],'convoy selector has an explicit cargo-bed contract')
check('shorad plan materialized','DRO2026_fnc_materializeStrategicSHORAD' in infra and 'SHORAD_FORMATION_MATERIALIZED' in shorad,'virtual plan must create bounded physical layers')
check('shorad can disable','(_maxSites max 0) min 4' in shorad and 'LIMIT_ZERO' in shorad,'zero physical limit must remain zero')
check('root classes never spawned','configClasses' in strategic and 'isKindOf [_rootClass' in strategic and '["SHORAD_EAST","pook_96K6_root"]' not in strategic and '"_root"' in shorad,'discover concrete descendants, never create root helpers')
check('shorad roles classified','"zu23"' in primary and '"_aa_f"' in primary and '"tungus"' in primary,'known gun/vehicle AA classes must classify as SHORAD')
check('site validation and cleanup','DRO2026_fnc_validateSiteRecord' in shorad and 'SITE_VALIDATION_FAILED' in shorad and '_cleanupObjects' in shorad,'activate plan only after valid physical site')
check('dynamic simulation order','_vehicle enableDynamicSimulation true;' in shorad and '_crewGroup enableDynamicSimulation true' in shorad and '_x enableDynamicSimulation true;' in layered and '_crewGroup enableDynamicSimulation true' in point,'vehicle before crew and AI group after crew')
check('placement order','setDir' in shorad and 'setVehiclePosition' in shorad and shorad.index('setDir') < shorad.index('setVehiclePosition'),'direction must be set before placement recalculation')
check('broken external classes blocked','b_afougf_old_ZU23' in sanitize and 'B_UAArmy_CAT1A2_01' in sanitize and 'setVariable ["DRO2026_runtimeBlockedVehicleClasses"' in sanitize and 'DRO2026_runtimeBlockedVehicleClasses' in layered and 'DRO2026_runtimeBlockedVehicleClasses' in point,'effective blocklist must reach every AA materializer')
check('mp header override','gameType = "Coop";' in description and 'maxPlayers = 8;' in description,'description.ext must expose all playable roles')
failed=[c for c in checks if not c['ok']]
print(json.dumps({'validator':'runtime-telemetry-remediation','passed':len(checks)-len(failed),'total':len(checks),'checks':checks},ensure_ascii=False,indent=2))
sys.exit(1 if failed else 0)
