'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path');
const { parseSqf, stringifySqf } = require('../src/sqf');
const { IniTransport } = require('../src/transport');
const { normalizeSnapshot, compactForPrompt } = require('../src/snapshot');
const { validateTactical, validateStrategic } = require('../src/validate');
const value=['decision',['TACTICAL_INTENT',7,'READY','C7','EXECUTE',5,1,2,true,900,30,'OK',100,'mock','mock']];
assert.deepEqual(parseSqf(stringifySqf(value)),value);
const raw=['0.1','TACTICAL_INTENT','MISSION_X',7,100,[['phase','DISRUPTION'],['doctrine','DRONE_HEAVY'],['alert',0.5]],[['fpsAverage',40],['activeDrones',1]],[['N1','FPV_TEAM','ACTIVE','UNKNOWN',1,[['FPV_KITS',3]],['FPV_ATTACK']]],[['E1','A','B','OPEN',0.2,0,0,120,['FPV_KITS']]],[['C1','PLAYER_GROUP',0.8,80,10,'CONFIRMED','',[1,0,0],0.8]],[[1,'CONTACT_UPDATED',5,'C1',[['confidence',0.8]]]],[['CAND_7_0','FPV_ATTACK','N1','C1',0.8,0.1,[['maxSalvo',2]]]],[['desiredTempo',0.5]]];
const normalized=normalizeSnapshot(raw); const prompt=compactForPrompt(normalized);
assert.equal(prompt.candidates[0].id,'CAND_7_0');
const valid=validateTactical({snapshotSequence:7,selectedCandidateId:'CAND_7_0',decision:'EXECUTE',delaySeconds:4,tempoModifier:1.1,actionModifiers:{salvoCount:9},reasonCode:'TEST'},prompt);
assert.equal(valid.actionModifiers.salvoCount,3);
assert.throws(()=>validateTactical({...valid,selectedCandidateId:'NOPE'},prompt),/UNKNOWN_CANDIDATE/);
const policy=validateStrategic({snapshotSequence:7,doctrine:'MOBILE_RESERVES',desiredTempo:2,priorities:['A']},prompt);
assert.equal(policy.desiredTempo,0.9);
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'droai-')); const t=new IniTransport(dir); t.ensureFiles(); t.send('ping',[1]);
fs.appendFileSync(path.join(dir,'DROAI_out.ini'),'req = ["snapshot",[1,2]]\r\n','utf8');
const entries=t.readOutgoing(); assert.equal(entries.length,1); t.release(['req']); assert.equal(t.readOutgoing().length,1); t.acknowledge(['req']); assert.equal(t.readOutgoing().length,0);
console.log('DRO2026 AI Director self-test passed');
